#MIAOW-7115 add citationContent
miaowrite/RTModel pull request #11
Opened 2020-10-26 04:03 UTC by DLinsh

2020-10-26 07:01 UTC, mwcshao requested changes

2020-10-26 07:01 UTC, mwcshao commented on model/SourceData.ts
> +interface ProcessedReferences extends BaseParagraphWithDecorates {
Is this just one reference, or multiple references?

2020-10-27 02:06 UTC, DLinsh commented on model/SourceData.ts
> +interface ProcessedReferences extends BaseParagraphWithDecorates {
应该是一个reference

2020-10-27 02:09 UTC, DLinsh commented
本次修改代码合入后还需要提交一次对RTWord中引用该接口部分的修改。

2020-10-27 02:12 UTC, merged